// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: jbURxL3XuiMBQsLhf7apui
// Component: QtxVTjIxZI
import * as React from "react";

import { Link, GatsbyLinkProps as LinkProps } from "gatsby";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import FathymFooter from "../../FathymFooter"; // plasmic-import: 3jTJ0D37Jf/component

import "@plasmicapp/react-web/lib/plasmic.css";

import * as plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import * as projectcss from "./plasmic_new_fathym_com.module.css"; // plasmic-import: jbURxL3XuiMBQsLhf7apui/projectcss
import * as sty from "./PlasmicUpdatedFathymFooter.module.css"; // plasmic-import: QtxVTjIxZI/css

export type PlasmicUpdatedFathymFooter__VariantMembers = {};

export type PlasmicUpdatedFathymFooter__VariantsArgs = {};
type VariantPropType = keyof PlasmicUpdatedFathymFooter__VariantsArgs;
export const PlasmicUpdatedFathymFooter__VariantProps =
  new Array<VariantPropType>();

export type PlasmicUpdatedFathymFooter__ArgsType = {};
type ArgPropType = keyof PlasmicUpdatedFathymFooter__ArgsType;
export const PlasmicUpdatedFathymFooter__ArgProps = new Array<ArgPropType>();

export type PlasmicUpdatedFathymFooter__OverridesType = {
  root?: p.Flex<typeof FathymFooter>;
};

export interface DefaultUpdatedFathymFooterProps {
  className?: string;
}

function PlasmicUpdatedFathymFooter__RenderFunc(props: {
  variants: PlasmicUpdatedFathymFooter__VariantsArgs;
  args: PlasmicUpdatedFathymFooter__ArgsType;
  overrides: PlasmicUpdatedFathymFooter__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  return (
    <FathymFooter
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames("__wab_instance", sty.root)}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: typeof FathymFooter;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicUpdatedFathymFooter__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicUpdatedFathymFooter__VariantsArgs;
    args?: PlasmicUpdatedFathymFooter__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicUpdatedFathymFooter__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicUpdatedFathymFooter__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicUpdatedFathymFooter__ArgProps,
          internalVariantPropNames: PlasmicUpdatedFathymFooter__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicUpdatedFathymFooter__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicUpdatedFathymFooter";
  } else {
    func.displayName = `PlasmicUpdatedFathymFooter.${nodeName}`;
  }
  return func;
}

export const PlasmicUpdatedFathymFooter = Object.assign(
  // Top-level PlasmicUpdatedFathymFooter renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicUpdatedFathymFooter
    internalVariantProps: PlasmicUpdatedFathymFooter__VariantProps,
    internalArgProps: PlasmicUpdatedFathymFooter__ArgProps
  }
);

export default PlasmicUpdatedFathymFooter;
/* prettier-ignore-end */
